config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products do
    collection do
      get 'buy'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :product
  belongs_to :client

  def self.sub_total
    joins(:product).sum("products.price")
  end

  def self.total_tax
    @total, @total_tax, @flags = 0, 0, 0
    @discount = false
    @baskets = Basket.all
    

    @baskets.each do |basket|
      
      # add taxes 
      if basket.product.vat_rate == "reduce"
       
        tax = (basket.product.price * 0.05)
        @total += (basket.product.price + tax)

        @total_tax += tax

      elsif basket.product.vat_rate == "standar"
        
        tax = (basket.product.price * 0.20)
        @total += (basket.product.price + tax )

        @total_tax += tax
      
      else #Zero
        
        @total += basket.product.price

      end
     
      # flag discount
      @flags += 1 if basket.product.product_code == 1
       
      if @flags > 0 && @flags % 2 == 0
        @total = (@total - 5.0)
      end

      # general discount
      if @total >= 70 &&  @discount == false
        discount = (@total * 0.12)
        @total = (@total - discount)
        @discount = true
      end

    end 

    puts "TOTAL = #{@total}"

    return @total
  end

end

app/models/client.rb
class Client < ApplicationRecord
  has_many :baskets
  has_many :products, :through => :baskets
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :baskets
  has_many :clients, :through => :baskets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_params, only: [:show]
  def index
    @products = Product.all
    @client = Client.find(1)
    @baskets = Basket.all
    @total = get_total
  end

  def show
    
  end

  def buy
    client_id, product_id = params[:client_id], params[:product_id] 

    @basket = Basket.new

    @basket.client_id = client_id

    @basket.product_id = product_id

    if @basket.save
      @baskets = Basket.all
      @total = get_total

      @save = true

    else
      @save = false

    end
  end

  private

  def get_total
    Basket.total_tax
  end

  def get_params
    @product = Product.find(params[:id])
  end

  def basket_params
    params.require(:basket).permit(:client_id, :product_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    end
    nil
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def convert_rate vat_type
    case vat_type
    when "zero"
      tax = "0%"
    when "reduce"
      tax = "5%"
    else
      tax = "20%"
    end
  end
 

  def tax_fees vat_type, amount
    case vat_type
    when "zero"
      total = "0"
    when "reduce"
      total = "#{(amount * 0.05)}"
    else
      total = "#{(amount * 0.20)}"
    end
  end 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_basket_errors.html.haml
.container
  = flash_messages

app/views/products/_basket_products.html.haml
%table.table
  %thead
    %tr
      %th Products
      %th Vat Rate
      %th Price
  %tbody
    - @baskets.each do |basket|
      %tr
        %td 
          = basket.product.name
        %td 
          = convert_rate(basket.product.vat_rate)
        %td 
          = number_to_currency(basket.product.price, unit: "£",)
  %tr
    %td SubTotal
    %td
    %td 
      = number_to_currency(@baskets.sub_total, unit: "£",)

  %tr
    %td Total
    %td
    %td 
      = number_to_currency(@total, unit: "£",)

app/views/products/_modal_product.html.haml
#modalProduct.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title 
          = @product.name
      .modal-body
        .container
          %table.col-md-8
            %tbody
              %tr
                %td
                  %strong Product Code
                %td
                %td 
                  = @product.product_code
              %tr
                %td
                  %strong Vat rate
                %td
                %td 
                  = convert_rate @product.vat_rate

              %tr
                %td
                  %strong Tax
                %td
                %td 
                  = tax_fees @product.vat_rate, @product.price

              %tr
                %td
                  %strong Details
                %td
                %td products
              
        .modal-footer
          .text-right.pull-right.col-md-3
            Price:
            %br/
            %span.h3.text-muted
              %strong 
                = number_to_currency @product.price, unit: "£"

      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/products/buy.js.erb
<% if @save %>
  $("#products_selected_js").html("<%= escape_javascript(render 'basket_products') %>");
<% else %>
  $("#Errors").html("<%= escape_javascript(render 'basket_errors') %>");
<% end %>

app/views/products/index.html.haml
.container
  %h1.page-header Products

  .container.centered
    - if @products.present?
      %ul.product_list
        - @products.each  do |product|
          %li
            = image_tag( product.pic , :class => "product_image", size: "190x180")
            .desc
              %p
                %strong
                  = product.name
              %p
                %span
                  = number_to_currency(product.price, unit: "£",)
              = link_to "View", product_path(product.id) , :class => "btn btn-success", remote: true
              = link_to "Add to Basket", buy_products_path(product_id: product.id, client_id: @client.id) , :class => "btn btn-warning", remote: true
    - else
      .alert.alert-danger
        %strong Please!
        Run rake db:seeds

.container
  %h1.page-header Basket 

  .panel.panel-default
    .panel-heading List of products
    .panel-body
      #products_selected_js
        = render 'basket_products'
#prouct_js

app/views/products/show.js.erb
$("#prouct_js").html("<%= escape_javascript(render 'modal_product') %>");

$("#modalProduct").modal('show');    